
server:
  port: 8085
spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pratik@123
    url: jdbc:mysql://localhost:3306/test1
    username: root
  jpa:
    hibernate:
      ddl-auto: update