
server:
  port: 8085
spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pratik@123
    url: jdbc:mysql://localhost:3306/test1
    username: root
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  hostname: localhost:8761
#  client:
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    statusPageUrl: http://${eureka.hostname}/info
#    healthCheckUrl: http://${eureka.hostname}/health
#    homePageUrl: http://${eureka.hostname}/
